movies/views.py
import os
import string
import random

from flask import render_template, Blueprint, url_for, request
from sqlalchemy.orm import aliased
from werkzeug.utils import secure_filename, redirect

from actors.models.actor import Actor
from app import app, db, csrf
from directors.models.director import Director
from images.models.Image import Image
from movies.forms import UpdateMovieForm, CreateMovieForm, CreateMovieRole
from movies.models.movie import Movie
from movies.models.movieRole import MovieRole

bp = Blueprint('movies', __name__, url_prefix='/movies', template_folder='templates')

@bp.get("/recent-added")
def showRecentAdded():
    movies = Movie.query.join(Movie.cover).order_by(Movie.id.desc()).all()
    return render_template('popular.html', movies=movies)


@bp.get("/recent")
def showRecentReleased():
    movies = Movie.query.join(Movie.cover).order_by(Movie.date.desc()).all()
    return render_template('recent.html', movies=movies)


@bp.get('/<int:id>')
def getMovie(id):
    cover = aliased(Image)
    banner = aliased(Image)
    movie = Movie.query.join(cover, Movie.cover)\
        .join(banner, Movie.banner)\
        .join(Movie.director)\
        .join(Movie.movieRole, MovieRole.actor, isouter=True)\
        .filter(Movie.id == id).first()
    return movie.toJson()


@bp.post('')
def createMovie():
    payload = CreateMovieForm()
    if not payload.validate():
        return redirect(url_for('movies.showRecentAdded'))
    cover_id = saveImage(request.files['cover'])
    banner_id = saveImage(request.files['banner'])
    title = payload.title.data
    description = payload.description.data
    date = payload.date.data
    directorFirstName = payload.directorFirstName.data
    directorLastName = payload.directorLastName.data
    director = Director.query.filter(Director.first_name == directorFirstName and Director.last_name == directorLastName).first()
    if not director:
        director = Director(directorFirstName, directorLastName)
        db.session.add(director)
        db.session.commit()
    movie = Movie(cover_id, banner_id, director.id, title, description, date)
    db.session.add(movie)
    db.session.commit()
    return redirect(url_for('movies.showRecentAdded'))



@bp.post('/<int:id>')
def updateMovie(id):
    payload = UpdateMovieForm()
    if not payload.validate():
        return redirect(url_for('movies.showRecentAdded'))
    movie = Movie.query.filter(Movie.id == id).first()
    if not movie:
        return redirect(url_for('movies.showRecentAdded'))
    old_cover_id = None
    old_banner_id = None
    if payload.title.data:
        movie.title = payload.title.data
    if payload.description.data:
        movie.description = payload.description.data
    if payload.date.data:
        movie.date = payload.date.data
    if payload.directorFirstName.data and payload.directorLastName.data:
        directorFirstName = payload.directorFirstName.data
        directorLastName = payload.directorLastName.data
        director = Director.query.filter(Director.first_name == directorFirstName).filter(Director.last_name == directorLastName).first()
        if not director:
            director = Director(directorFirstName, directorLastName)
            db.session.add(director)
            db.session.commit()
        movie.director_id = director.id
    if request.files['cover']:
        cover_id = saveImage(request.files['cover'])
        old_cover_id = movie.cover_id
        movie.cover_id = cover_id
    if request.files['banner']:
        banner_id = saveImage(request.files['banner'])
        old_banner_id = movie.banner_id
        movie.banner_id = banner_id
    db.session.add(movie)
    db.session.commit()
    if old_cover_id:
        Image.delete(old_cover_id)
    if old_banner_id:
        Image.delete(old_banner_id)
    return redirect(url_for('movies.showRecentAdded'))

@csrf.exempt
@bp.post('/<int:id>/role')
def addRole(id):
    payload = CreateMovieRole()
    if not payload.validate():
        return payload.errors
    first_name = payload.first_name.data
    last_name = payload.last_name.data
    role = payload.role.data
    existingActor = Actor.query.filter(Actor.first_name == first_name).filter(Actor.last_name == last_name).first()
    if not existingActor:
        existingActor = Actor(first_name, last_name)
        db.session.add(existingActor)
        db.session.commit()
    movieRole = MovieRole(id, existingActor.id, role)
    db.session.add(movieRole)
    db.session.commit()
    return {
        'id': movieRole.id,
        'first_name': existingActor.first_name,
        'last_name': existingActor.last_name,
        'role': movieRole.name
    }

@csrf.exempt
@bp.post('/<int:id>/role/<int:roleId>/delete')
def removeRol(id, roleId):
    MovieRole.query.filter(MovieRole.id == roleId).delete()
    db.session.commit()
    return {}


def saveImage(file):
    filename = secure_filename(file.filename)
    extension = filename.split('.')[-1]
    file_name = ''.join(random.choice(string.ascii_lowercase) for i in range(16)) + "." + extension
    file.save(os.path.join(app.config['UPLOAD_FOLDER'], file_name))
    image = Image(file_name)
    db.session.add(image)
    db.session.flush()
    return image.id

profile/views.py
from flask import render_template, Blueprint

bp = Blueprint('profile', __name__, template_folder='templates')


@bp.get("/profile")
def showProfile():
    return render_template('profile.html')

templates/base.html
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href='https://fonts.googleapis.com/css?family=JetBrains Mono' rel='stylesheet'>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
  {% block head %}{% endblock %}
</head>
<body>
<div class="d-flex flex-column side-bar p-3 text-white bg-dark">
  <img class="responsive" src="{{url_for('static', filename='images/icon.png')}}"/>
  <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{{ url_for('movies.showRecentAdded') }}"  class="nav-link {{ 'active' if active_page == 'recentAdded' else '' }}">
          Recent Toegevoegd
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ url_for('movies.showRecentReleased') }}"  class="nav-link {{ 'active' if active_page == 'recentReleased' else '' }}">
          Recent Gereleased
        </a>
      </li>
    </ul>
    {% if current_user.is_authenticated  %}
    <div class="dropdown logout">
      <hr>
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="{{url_for('static', filename='images/user_icon.png')}}" width="24" height="24" class="rounded-circle me-2">
        <strong>{{current_user.email}}</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item {{ 'active' if active_page == 'profile' else '' }}" href="{{ url_for('profile.showProfile') }}">Profiel</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Uitloggen</a></li>
      </ul>
  </div>
  {% else %}
  <div>
    <a href="{{ url_for('auth.login') }}">
      <button class="btn btn-primary w-100">Log in</button>
    </a>
  </div>
  {% endif %}
</div>
<div class="main-container">
  {% block content %}{% endblock %}
</div>
<script src="{{url_for('static', filename='js/bootstrap.js')}}" crossorigin="anonymous"></script>
{% block body %}{% endblock %}
</body>
</html>